version: "3.8"
services:
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.test
        networks:
            - backend
        depends_on:
            - db
        cap_add:
            - SYSLOG
        cap_drop:
            - SYS_ADMIN
        restart: "no"
    db:
        build:
            context: ./database
            dockerfile: Dockerfile.test
        expose:
            - "5432"
        volumes:
            - db-data-test:/var/lib/postgresql/data
        networks:
            - backend
        cap_add:
            - SYSLOG
        cap_drop:
            - SYS_ADMIN
        logging:
            driver: none
        restart: on-failure

networks:
    # frontend:
    backend:

volumes:
    db-data-test: